<?php

namespace ZIMZIM\Bundles\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getList($source, SecurityContext $securityContext, $id_tournament){

        $tableAlias = $source->getTableAlias();

        $source->manipulateQuery(
            function ($query) use ($tableAlias, $securityContext, $id_tournament) {

                return $query
                    ->andWhere($tableAlias.'.tournament = :id_tournament')
                    ->setParameter('id_tournament', $id_tournament);
            }
        );
        return $source;
    }
}
