<?php

namespace ZIMZIM\Bundles\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use ZIMZIM\Bundles\AppBundle\Entity\UserTournament;


/**
 * RequestUserRankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestUserRankingRepository extends EntityRepository
{

    public function getRankingByUserTournament(UserTournament $userTournament){

        $query  = $this->createQueryBuilder('r');

        $query->join('r.requestUser', 'ru')
            ->join('ru.userTournament', 'ut')
            ->where('ru.enabled = 1 ')
            ->andWhere('ru.validate = 1 ')
            ->andWhere('ut.id = :tournament')
            ->setParameter('tournament', $userTournament)
            ->orderBy('r.score', 'DESC')
            ->addOrderBy('r.nbMaxScore', 'DESC');

        return $query->getQuery()->getResult();

    }
}
