<?php

namespace ZIMZIM\Bundles\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\SecurityContext;
use ZIMZIM\Bundles\AppBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestUserRepository extends EntityRepository
{

    public function getByUserAndTournament($user, $tournament){

        $query = $this->createQueryBuilder('ru');
        $query->join('ru.user', 'u')
            ->join('ru.userTournament', 'ut')
            ->join('ut.tournament', 't')
            ->where('t.id = :tournament')
            ->andWhere('u.id = :user')
            ->setParameter('tournament', $tournament->getId())
            ->setParameter('user', $user->getId());

        return $query->getQuery()->getResult();

    }


    public function getEnabledByGame(Game $game){

        $query = $this->createQueryBuilder('ru');
        $query->join('ru.user', 'u')
            ->join('ru.userTournament', 'ut')
            ->join('ut.tournament', 't')
            ->join('t.games', 'g')
            ->where('g = :game')
            ->andWhere('ut.enabled = 1')
            ->andWhere('ru.enabled = 1')
            ->andWhere('t.enabled = 1')
            ->andWhere('u.enabled = 1')
            ->setParameter('game', $game);
        
        return $query->getQuery()->getResult();
    }


}
