fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ZIMZIM\Bundles\UserBundle\Entity\User
    registration:
        form:
            type: zimzim_user_registration
    profile:
        form:
            type: zimzim_user_profile