fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            xml: false
            json: true
            rss: false
            yml: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true