security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_SCORE: [ ROLE_USER, ROLE_SCORE ]
        ROLE_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_SCORE ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    google: "/user/login/check-google"
                    facebook: "/user/login/check-facebook"
                    twitter: "/user/login/check-twitter"
                login_path: /user/login/
                failure_path: /user/login/

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
                    #service: hwi_oauth.user.provider.entity
            logout: true
            anonymous: true

        login:
            pattern: ^/login$
            security: false
            form_login:
                always_use_default_target_path: true
                default_target_path: /game/

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/requestuser/[0-9]*/join/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/requestuser/, role: ROLE_USER }
        - { path: ^/usertournament/, role: ROLE_USER }