zimzim_bundles_app_requestuser:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:index" }

zimzim_bundles_app_requestuser_show:
    pattern:  /{id}/show
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:show" }

zimzim_bundles_app_requestuser_new:
    pattern:  /new
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:new" }

zimzim_bundles_app_requestuser_create:
    pattern:  /create
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:create" }
    requirements: { _method: post }

zimzim_bundles_app_requestuser_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:edit" }

zimzim_bundles_app_requestuser_update:
    pattern:  /{id}/update
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:update" }
    requirements: { _method: post|put }

zimzim_bundles_app_requestuser_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:delete" }
    requirements: { _method: post|delete }
