zimzim_bundles_app_requestuser:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:index" }
    requirements: { _method: get }

zimzim_bundles_app_requestuser_update:
    pattern:  /{id}/update/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:update" }
    requirements: { _method: post|put }

zimzim_bundles_app_requestuser_delete:
    pattern:  /{id}/delete/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:delete" }
    requirements: { _method: post|delete }

zimzim_bundles_app_requestuser_join:
    pattern:  /{id}/join/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:join" }
    requirements: { _method: get|post }

zimzim_bundles_app_requestuser_enabledvalidate:
    pattern:  /{id}/enabledvalidate/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:enabledvalidate" }
    requirements: { _method: get|post }

zimzim_bundles_app_requestuser_sendrequest:
    pattern:  /{id}/sendrequest/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:RequestUser:sendrequest" }
    requirements: { _method: get|post }