zimzim_bundles_app_usertournament:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesAppBundle:UserTournament:index" }

zimzim_bundles_app_usertournament_newuser:
    pattern:  /{id}/newuser/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:UserTournament:newuser" }
    requirements: { _method: get|post }

zimzim_bundles_app_usertournament_updateuser:
    pattern:  /{id}/updateuser/
    defaults: { _controller: "ZIMZIMBundlesAppBundle:UserTournament:updateuser" }
    requirements: { _method: get|post }