services:
    zimzim_bundles_app.listener.registerclientgamesubscriber:
        class: ZIMZIM\Bundles\AppBundle\EventListener\UserTournamentSubscriber
        arguments: [ @doctrine.orm.entity_manager, @zimzim_bundles_app.entity.requestuser ]
        tags:
            - { name: kernel.event_subscriber }

    zimzim_bundles_app.event.usertournamentevent:
        class: ZIMZIM\Bundles\AppBundle\Event\UserTournamentEvent

    zimzim_bundles_app.listener.joinrequestusersubscriber:
        class: ZIMZIM\Bundles\AppBundle\EventListener\RequestUserSubscriber
        arguments: [ @doctrine.orm.entity_manager, @security.context, @session, @router ]
        tags:
            - { name: kernel.event_subscriber }

    zimzim_bundles_app.listener.requestuseremailsubscriber:
        class: ZIMZIM\Bundles\AppBundle\EventListener\RequestUserEmailSubscriber
        arguments: [ @mailer, @templating, @translator ]
        tags:
            - { name: kernel.event_subscriber }

    zimzim_bundles_app.listener.requestuserbetsubscriber:
        class: ZIMZIM\Bundles\AppBundle\EventListener\GameUpdateSubscriber
        arguments: [ @doctrine.orm.entity_manager, @zimzim_bundles_app.calculate.score ]
        tags:
            - { name: kernel.event_subscriber }

    zimzim_bundles_app.listener.gameupdatesubscriber:
        class: ZIMZIM\Bundles\AppBundle\EventListener\RequestUserBetSubscriber
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: kernel.event_subscriber }

    zimzim_bundles_app.event.requestuserevent:
        class: ZIMZIM\Bundles\AppBundle\Event\RequestUserEvent
    zimzim_bundles_app.event.requestuserbetevent:
        class: ZIMZIM\Bundles\AppBundle\Event\RequestUserBetEvent
    zimzim_bundles_app.event.gameevent:
        class: ZIMZIM\Bundles\AppBundle\Event\GameEvent