zimzim_bundles_app:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/home.yml"
    prefix:   /

ZIMZIMBundlesAppBundle_zimzim_bundles_app_tournament:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/tournament.yml"
    prefix:   /admin/tournament/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_adminusertournament:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/adminusertournament.yml"
    prefix:   /admin/usertournament/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_usertournament:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/usertournament.yml"
    prefix:   /usertournament/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_adminrequestuser:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/adminrequestuser.yml"
    prefix:   /admin/requestuser/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_requestuser:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/requestuser.yml"
    prefix:   /requestuser/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_adminteam:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/adminteam.yml"
    prefix:   /admin/team/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_tournamentday:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/tournamentday.yml"
    prefix:   /admin/tournamentday/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_admingame:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/admingame.yml"
    prefix:   /admin/game/

ZIMZIMBundlesAppBundle_zimzim_bundles_app_game:
    resource: "@ZIMZIMBundlesAppBundle/Resources/config/routing/game.yml"
    prefix:   /game/